### ISSUE TITLE
scrom

### ISSUE THREAD

**Issue by suraj484** [DadUndead/ngx-scorm-wrapper-demo#1]
after clone the code and run ng run build into terminal getting error message
Failed to load external module @babel/register
Requiring external module babel-register
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (G:\ngx-scorm-wrapper-demo\node_modules\natives\index.js:143:24)
    at Object.req [as require] (G:\ngx-scorm-wrapper-demo\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (G:\ngx-scorm-wrapper-demo\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (G:\ngx-scorm-wrapper-demo\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-scorm-wrapper-demo@0.0.1 manifest: `gulp manifest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngx-scorm-wrapper-demo@0.0.1 manifest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-07-05T05_54_19_575Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-scorm-wrapper-demo@0.0.1 build: `ng build && npm run manifest && npm run zip`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngx-scorm-wrapper-demo@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-07-05T05_54_19_680Z-debug.log

**Comment by Gajendrasinh** [comment]
Hello

Any workaround in above issue, I am also getting same error.
